# Generated by Django 4.2.6 on 2023-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumePage', '0002_remove_work_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiilsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='description',
        ),
    ]
