# Generated by Django 4.2.6 on 2023-10-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumePage', '0003_skiilsdescription_remove_skills_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='txt',
            new_name='description',
        ),
    ]
