# Generated by Django 4.2.6 on 2023-10-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumePage', '0005_kore_delete_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kore',
            new_name='More',
        ),
    ]
