# Generated by Django 4.2.6 on 2023-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumePage', '0006_rename_kore_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='degree',
            field=models.CharField(max_length=350, verbose_name='Job'),
        ),
    ]
