# Generated by Django 4.2.6 on 2023-11-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumePage', '0007_alter_work_degree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='More',
            new_name='MoreText',
        ),
    ]
