# Generated by Django 4.2.6 on 2023-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aboutme', models.CharField(max_length=350, verbose_name='Title(Aboutme)')),
                ('DescriptionAboutme', models.TextField(verbose_name='Description(Aboutme)')),
                ('ContactDetails', models.CharField(max_length=350, verbose_name='Title(ContactDetails)')),
                ('Name', models.CharField(max_length=350, verbose_name='Name')),
                ('Address', models.CharField(max_length=350, verbose_name='Address')),
                ('PhoneNumber', models.CharField(max_length=350, verbose_name='PhoneNumber')),
                ('Email', models.EmailField(max_length=350, verbose_name='Email')),
            ],
        ),
    ]
