# Generated by Django 4.2.6 on 2023-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutPage', '0002_aboutme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='pic', upload_to='static/media', verbose_name='profile'),
        ),
    ]
