# Generated by Django 4.2.6 on 2023-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutPage', '0003_alter_aboutme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(upload_to='static/media', verbose_name='Resume File')),
            ],
        ),
    ]
