# Generated by Django 4.2.6 on 2023-11-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutPage', '0004_upresume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpResume',
            new_name='Update_Resume',
        ),
    ]
