# Generated by Django 4.2.6 on 2023-11-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutPage', '0005_rename_upresume_update_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='pic', upload_to='staticfiles/media', verbose_name='profile'),
        ),
    ]
