# Generated by Django 4.2.6 on 2023-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstcopyright', models.CharField(max_length=350, verbose_name='copyrights 1')),
                ('secondcopyright', models.CharField(max_length=350, verbose_name='copyrights 2')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('title', models.CharField(max_length=350, verbose_name='title(address and phone)')),
                ('title2', models.CharField(max_length=350, verbose_name='title(Latest Tweets)')),
                ('description2', models.TextField(verbose_name='description(Latest Tweets)')),
                ('date', models.DateField(max_length=350, verbose_name='date for (Latest Tweets)')),
            ],
        ),
    ]
