# Generated by Django 4.2.6 on 2023-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0002_remove_info_title2_alter_info_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='descrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description(Latest Tweets)')),
                ('date', models.DateField(max_length=350, verbose_name='date for (Latest Tweets)')),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
        migrations.RemoveField(
            model_name='info',
            name='description2',
        ),
    ]
