# Generated by Django 4.2.6 on 2023-10-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='descrip',
            new_name='Copyright',
        ),
    ]
