# Generated by Django 4.2.6 on 2023-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0005_rename_descrip_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='descrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description(Latest Tweets)')),
                ('date', models.DateField(max_length=350, verbose_name='date for (Latest Tweets)')),
            ],
        ),
        migrations.DeleteModel(
            name='footer',
        ),
        migrations.RemoveField(
            model_name='copyright',
            name='date',
        ),
        migrations.RemoveField(
            model_name='copyright',
            name='description',
        ),
        migrations.AddField(
            model_name='copyright',
            name='firstcopyright',
            field=models.CharField(default='COPYRIGHT', max_length=350, verbose_name='copyrights 1'),
        ),
        migrations.AddField(
            model_name='copyright',
            name='secondcopyright',
            field=models.CharField(default='COPYRIGHT', max_length=350, verbose_name='copyrights 2'),
        ),
    ]
