# Generated by Django 4.2.6 on 2023-10-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0006_descrip_delete_footer_remove_copyright_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUsReceiveForm',
        ),
    ]
