# Generated by Django 4.2.6 on 2023-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0007_rename_contact_contactusreceiveform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='title',
        ),
        migrations.AddField(
            model_name='descrip',
            name='title',
            field=models.CharField(max_length=350, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='descrip',
            name='date',
            field=models.DateField(max_length=350, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='descrip',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
