# Generated by Django 4.2.6 on 2023-11-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0008_remove_info_title_descrip_title_alter_descrip_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descrip',
            name='title',
        ),
    ]
