# Generated by Django 4.2.6 on 2023-10-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('facebook', models.CharField(max_length=500, verbose_name='facebook')),
                ('twitter', models.CharField(max_length=500, verbose_name='twitter')),
                ('googleplus', models.CharField(max_length=500, verbose_name='googleplus')),
                ('linkedin', models.CharField(max_length=500, verbose_name='linkedin')),
                ('instagram', models.CharField(max_length=500, verbose_name='instagram')),
                ('link', models.CharField(max_length=500, verbose_name='link')),
                ('skype', models.CharField(max_length=500, verbose_name='skype')),
            ],
        ),
    ]
