# Generated by Django 4.2.6 on 2023-10-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_remove_header_link_alter_header_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='header',
            new_name='intruce',
        ),
    ]
