# Generated by Django 4.2.6 on 2023-10-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_rename_header_intruce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='intruce',
            new_name='intruduce',
        ),
    ]
